
package com.gameco.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Fri Jun 03 01:53:06 SAMT 2016
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "CredentialException", namespace = "http://network.gameco.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CredentialException", namespace = "http://network.gameco.com/")

public class CredentialExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

