
package com.gameco.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Fri Jun 03 01:53:05 SAMT 2016
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "getGamesResponse", namespace = "http://server.gameco.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGamesResponse", namespace = "http://server.gameco.com/")

public class GetGamesResponse {

    @XmlElement(name = "return")
    private java.util.List<com.gameco.server.PlayingGame> _return;

    public java.util.List<com.gameco.server.PlayingGame> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.gameco.server.PlayingGame> new_return)  {
        this._return = new_return;
    }

}

