
package com.gameco.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T02:19:39.897+04:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "CredentialException", targetNamespace = "http://server.gameco.com/")
public class CredentialException_Exception extends Exception {
    
    private com.gameco.server.CredentialException credentialException;

    public CredentialException_Exception() {
        super();
    }
    
    public CredentialException_Exception(String message) {
        super(message);
    }
    
    public CredentialException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CredentialException_Exception(String message, com.gameco.server.CredentialException credentialException) {
        super(message);
        this.credentialException = credentialException;
    }

    public CredentialException_Exception(String message, com.gameco.server.CredentialException credentialException, Throwable cause) {
        super(message, cause);
        this.credentialException = credentialException;
    }

    public com.gameco.server.CredentialException getFaultInfo() {
        return this.credentialException;
    }
}
