
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.gameco.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T02:19:39.903+04:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "GameExchangeService",
                      portName = "GameExchangeServicePort",
                      targetNamespace = "http://server.gameco.com/",
                      wsdlLocation = "file:/P:/prjct/GamesEcosystem/Server/src/main/webapp/wsdl/gameexchangeservice.wsdl",
                      endpointInterface = "com.gameco.server.IGameExchangeService")
                      
public class GameExchangeServicePortImpl implements IGameExchangeService {

    private static final Logger LOG = Logger.getLogger(GameExchangeServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#setMoves(com.gameco.server.GameHistory  arg0 )*
     */
    public void setMoves(com.gameco.server.GameHistory arg0) { 
        LOG.info("Executing operation setMoves");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#setMove(com.gameco.server.GameMove  arg0 )*
     */
    public void setMove(com.gameco.server.GameMove arg0) { 
        LOG.info("Executing operation setMove");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#getGames(*
     */
    public java.util.List<com.gameco.server.PlayingGame> getGames() { 
        LOG.info("Executing operation getGames");
        try {
            java.util.List<com.gameco.server.PlayingGame> _return = new java.util.ArrayList<com.gameco.server.PlayingGame>();
            com.gameco.server.PlayingGame _returnVal1 = new com.gameco.server.PlayingGame();
            _returnVal1.setGameID("GameID-1921681972");
            java.util.List<com.gameco.server.User> _returnVal1Players = new java.util.ArrayList<com.gameco.server.User>();
            com.gameco.server.User _returnVal1PlayersVal1 = new com.gameco.server.User();
            _returnVal1PlayersVal1.setUsername("Username-172612175");
            _returnVal1PlayersVal1.setSessionID("SessionID-1073549938");
            java.util.List<java.lang.String> _returnVal1PlayersVal1AvaibleGame = new java.util.ArrayList<java.lang.String>();
            _returnVal1PlayersVal1.getAvaibleGame().addAll(_returnVal1PlayersVal1AvaibleGame);
            com.gameco.server.Callback _returnVal1PlayersVal1Callback = null;
            _returnVal1PlayersVal1.setCallback(_returnVal1PlayersVal1Callback);
            com.gameco.server.GameContainer _returnVal1PlayersVal1Game = null;
            _returnVal1PlayersVal1.setGame(_returnVal1PlayersVal1Game);
            _returnVal1Players.add(_returnVal1PlayersVal1);
            _returnVal1.getPlayers().addAll(_returnVal1Players);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#invite(java.util.List<java.lang.String>  arg0 )*
     */
    public void invite(java.util.List<java.lang.String> arg0) { 
        LOG.info("Executing operation invite");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#join(java.lang.String  arg0 )*
     */
    public void join(java.lang.String arg0) { 
        LOG.info("Executing operation join");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#getUsers(*
     */
    public java.util.List<com.gameco.server.User> getUsers() { 
        LOG.info("Executing operation getUsers");
        try {
            java.util.List<com.gameco.server.User> _return = new java.util.ArrayList<com.gameco.server.User>();
            com.gameco.server.User _returnVal1 = new com.gameco.server.User();
            _returnVal1.setUsername("Username-1010857791");
            _returnVal1.setSessionID("SessionID-1615391727");
            java.util.List<java.lang.String> _returnVal1AvaibleGame = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1AvaibleGameVal1 = "_returnVal1AvaibleGameVal109969659";
            _returnVal1AvaibleGame.add(_returnVal1AvaibleGameVal1);
            _returnVal1.getAvaibleGame().addAll(_returnVal1AvaibleGame);
            com.gameco.server.Callback _returnVal1Callback = null;
            _returnVal1.setCallback(_returnVal1Callback);
            com.gameco.server.GameContainer _returnVal1Game = null;
            _returnVal1.setGame(_returnVal1Game);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#logout(*
     */
    public void logout() { 
        LOG.info("Executing operation logout");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#addCallback(javax.xml.ws.wsaddressing.W3CEndpointReference  arg0 )*
     */
    public void addCallback(javax.xml.ws.wsaddressing.W3CEndpointReference arg0) { 
        LOG.info("Executing operation addCallback");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#accept(java.lang.String  arg0 )*
     */
    public void accept(java.lang.String arg0) { 
        LOG.info("Executing operation accept");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#getAvaibleGames(*
     */
    public java.util.List<java.lang.String> getAvaibleGames() { 
        LOG.info("Executing operation getAvaibleGames");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-1680121237";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#login(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public com.gameco.server.User login(java.lang.String arg0,java.lang.String arg1) throws CredentialException_Exception    { 
        LOG.info("Executing operation login");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            com.gameco.server.User _return = new com.gameco.server.User();
            _return.setUsername("Username673521756");
            _return.setSessionID("SessionID1529479878");
            java.util.List<java.lang.String> _returnAvaibleGame = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnAvaibleGameVal1 = "_returnAvaibleGameVal633772149";
            _returnAvaibleGame.add(_returnAvaibleGameVal1);
            _return.getAvaibleGame().addAll(_returnAvaibleGame);
            com.gameco.server.Callback _returnCallback = null;
            _return.setCallback(_returnCallback);
            com.gameco.server.GameContainer _returnGame = null;
            _return.setGame(_returnGame);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CredentialException_Exception("CredentialException...");
    }

    /* (non-Javadoc)
     * @see com.gameco.server.IGameExchangeService#cancel(java.lang.String  arg0 )*
     */
    public void cancel(java.lang.String arg0) { 
        LOG.info("Executing operation cancel");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
