package com.gameco.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T02:19:39.915+04:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://server.gameco.com/", name = "IGameExchangeService")
@XmlSeeAlso({ObjectFactory.class})
public interface IGameExchangeService {

    @WebMethod(action = "urn:SetMoves")
    @RequestWrapper(localName = "setMoves", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.SetMoves")
    @ResponseWrapper(localName = "setMovesResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.SetMovesResponse")
    public void setMoves(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gameco.server.GameHistory arg0
    );

    @WebMethod(action = "urn:SetMove")
    @RequestWrapper(localName = "setMove", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.SetMove")
    @ResponseWrapper(localName = "setMoveResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.SetMoveResponse")
    public void setMove(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gameco.server.GameMove arg0
    );

    @WebMethod(action = "urn:GetGames")
    @RequestWrapper(localName = "getGames", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetGames")
    @ResponseWrapper(localName = "getGamesResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetGamesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.gameco.server.PlayingGame> getGames();

    @WebMethod(action = "urn:Invite")
    @RequestWrapper(localName = "invite", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Invite")
    @ResponseWrapper(localName = "inviteResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.InviteResponse")
    public void invite(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebMethod(action = "urn:Join")
    @RequestWrapper(localName = "join", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Join")
    @ResponseWrapper(localName = "joinResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.JoinResponse")
    public void join(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(action = "urn:GetUsers")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.gameco.server.User> getUsers();

    @WebMethod(action = "urn:Logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.LogoutResponse")
    public void logout();

    @WebMethod(action = "urn:AddCallback")
    @RequestWrapper(localName = "addCallback", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.AddCallback")
    @ResponseWrapper(localName = "addCallbackResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.AddCallbackResponse")
    public void addCallback(
        @WebParam(name = "arg0", targetNamespace = "")
        javax.xml.ws.wsaddressing.W3CEndpointReference arg0
    );

    @WebMethod(action = "urn:Accept")
    @RequestWrapper(localName = "accept", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Accept")
    @ResponseWrapper(localName = "acceptResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.AcceptResponse")
    public void accept(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(action = "urn:GetAvaibleGames")
    @RequestWrapper(localName = "getAvaibleGames", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetAvaibleGames")
    @ResponseWrapper(localName = "getAvaibleGamesResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.GetAvaibleGamesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getAvaibleGames();

    @WebMethod(action = "urn:Login")
    @RequestWrapper(localName = "login", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.gameco.server.User login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws CredentialException_Exception;

    @WebMethod(action = "urn:Cancel")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://server.gameco.com/", className = "com.gameco.server.CancelResponse")
    public void cancel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
