
package com.gameco.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-03T02:19:39.845+04:00
 * Generated source version: 3.1.6
 * 
 */
public final class IGameExchangeService_GameExchangeServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.gameco.com/", "GameExchangeService");

    private IGameExchangeService_GameExchangeServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GameExchangeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GameExchangeService ss = new GameExchangeService(wsdlURL, SERVICE_NAME);
        IGameExchangeService port = ss.getGameExchangeServicePort();  
        
        {
        System.out.println("Invoking setMoves...");
        com.gameco.server.GameHistory _setMoves_arg0 = new com.gameco.server.GameHistory();
        java.util.List<com.gameco.server.GameMove> _setMoves_arg0Moves = new java.util.ArrayList<com.gameco.server.GameMove>();
        com.gameco.server.GameMove _setMoves_arg0MovesVal1 = new com.gameco.server.GameMove();
        _setMoves_arg0MovesVal1.setNumber(-1978555285);
        com.gameco.server.Duration _setMoves_arg0MovesVal1Duration = new com.gameco.server.Duration();
        _setMoves_arg0MovesVal1.setDuration(_setMoves_arg0MovesVal1Duration);
        _setMoves_arg0MovesVal1.setType("Type-1836697638");
        java.util.List<java.lang.String> _setMoves_arg0MovesVal1Moves = new java.util.ArrayList<java.lang.String>();
        _setMoves_arg0MovesVal1.getMoves().addAll(_setMoves_arg0MovesVal1Moves);
        _setMoves_arg0Moves.add(_setMoves_arg0MovesVal1);
        _setMoves_arg0.getMoves().addAll(_setMoves_arg0Moves);
        port.setMoves(_setMoves_arg0);


        }
        {
        System.out.println("Invoking setMove...");
        com.gameco.server.GameMove _setMove_arg0 = new com.gameco.server.GameMove();
        _setMove_arg0.setNumber(558830822);
        com.gameco.server.Duration _setMove_arg0Duration = new com.gameco.server.Duration();
        _setMove_arg0.setDuration(_setMove_arg0Duration);
        _setMove_arg0.setType("Type2052958627");
        java.util.List<java.lang.String> _setMove_arg0Moves = new java.util.ArrayList<java.lang.String>();
        java.lang.String _setMove_arg0MovesVal1 = "_setMove_arg0MovesVal144107722";
        _setMove_arg0Moves.add(_setMove_arg0MovesVal1);
        _setMove_arg0.getMoves().addAll(_setMove_arg0Moves);
        port.setMove(_setMove_arg0);


        }
        {
        System.out.println("Invoking getGames...");
        java.util.List<com.gameco.server.PlayingGame> _getGames__return = port.getGames();
        System.out.println("getGames.result=" + _getGames__return);


        }
        {
        System.out.println("Invoking invite...");
        java.util.List<java.lang.String> _invite_arg0 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _invite_arg0Val1 = "_invite_arg0Val14864022";
        _invite_arg0.add(_invite_arg0Val1);
        port.invite(_invite_arg0);


        }
        {
        System.out.println("Invoking join...");
        java.lang.String _join_arg0 = "_join_arg0-1169632800";
        port.join(_join_arg0);


        }
        {
        System.out.println("Invoking getUsers...");
        java.util.List<com.gameco.server.User> _getUsers__return = port.getUsers();
        System.out.println("getUsers.result=" + _getUsers__return);


        }
        {
        System.out.println("Invoking logout...");
        port.logout();


        }
        {
        System.out.println("Invoking addCallback...");
        javax.xml.ws.wsaddressing.W3CEndpointReference _addCallback_arg0 = null;
        port.addCallback(_addCallback_arg0);


        }
        {
        System.out.println("Invoking accept...");
        java.lang.String _accept_arg0 = "_accept_arg0-274593300";
        port.accept(_accept_arg0);


        }
        {
        System.out.println("Invoking getAvaibleGames...");
        java.util.List<java.lang.String> _getAvaibleGames__return = port.getAvaibleGames();
        System.out.println("getAvaibleGames.result=" + _getAvaibleGames__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "_login_arg0-456096583";
        java.lang.String _login_arg1 = "_login_arg1-1822717122";
        try {
            com.gameco.server.User _login__return = port.login(_login_arg0, _login_arg1);
            System.out.println("login.result=" + _login__return);

        } catch (CredentialException_Exception e) { 
            System.out.println("Expected exception: CredentialException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancel...");
        java.lang.String _cancel_arg0 = "_cancel_arg01653353650";
        port.cancel(_cancel_arg0);


        }

        System.exit(0);
    }

}
